INSERT INTO PERMISSION (PERMISSION_ID, permission) VALUES ('1', 'PERM_VIEW_USER');

INSERT INTO ROLE (USER_ROLE_ID, role) VALUES ('1', 'TEST');

INSERT INTO ROLE_PERMISSION (USER_ROLE_ID, PERMISSION_ID) VALUES ('1', '1');